### ISSUE TITLE
textColor does not appear to work

### ISSUE THREAD

**Issue by koitsu** [johnvictorfs/simple-utilities-mod#16]
Tried editing `.minecraft/config/simple_utilities.toml` and using `textColor = 16777215` (i.e. `0xffffff`, white) -- text is still the default gray (`0xe0e0e0`).

**Comment by johnvictorfs** [comment]
Thanks for reporting, will look into it

**Comment by koitsu** [comment]
As of version 2.2.0, this now appears to be working correctly when changed via Mod Menu.  Gonna close this one out.  Thanks!
