### ISSUE TITLE
Mod name in mod menu

### ISSUE THREAD

**Issue by PhoenixIV** [johnvictorfs/simple-utilities-mod#20]
I suggest you use the same plugin name both on Curseforge and ingame. I prefer "HUD utilities". I got a little confused when your plugin did not show up in my mods menu, until I noticed it has a different name.

**Comment by johnvictorfs** [comment]
Updated in version 2.1.2

https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/2.1.2
https://www.curseforge.com/minecraft/mc-mods/simple-utilities/files/3334439
