### ISSUE TITLE
Remove spoiler in menu

### ISSUE THREAD

**Issue by PhoenixIV** [johnvictorfs/simple-utilities-mod#21]
When I open the settings menu I first have to click "+", which makes no sense to me, as the only reason I access the menu is that I want to see the settings. There are no other options other than "HUD elements", so every redundant click is one too much ;-)

**Comment by johnvictorfs** [comment]
That's a good point, I planned on adding more advanced settings when I made that decision, but that ended up not happening, so that's indeed a pointless sub-menu

**Comment by johnvictorfs** [comment]
Updated in version 2.1.2

https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/2.1.2
https://www.curseforge.com/minecraft/mc-mods/simple-utilities/files/3334439
