### ISSUE TITLE
"All HUD elements" button unclear

### ISSUE THREAD

**Issue by PhoenixIV** [johnvictorfs/simple-utilities-mod#22]
I first thought that the button "All HUD elements" toggles all settings. Rename it to "Show HUD", maybe? Seems more clear to me.

**Comment by johnvictorfs** [comment]
Updated in version 2.1.2

https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/2.1.2
https://www.curseforge.com/minecraft/mc-mods/simple-utilities/files/3334439
