### ISSUE TITLE
Client crash when using Mod Menu

### ISSUE THREAD

**Issue by koitsu** [johnvictorfs/simple-utilities-mod#28]
Attempted to use Simple HUD Utilities 2.1.3 with Mod Menu 2.0.0-beta.7 on Minecraft 1.17.  When clicking in Mod Menu the configuration button for Simple HUD Utilities, Minecraft client crashed.  Stack trace:

> The game crashed whilst mouseclicked event handler
> Error: java.lang.IllegalAccessError: class me.shedaniel.clothconfig2.gui.ClothConfigScreen tried to access private field net.minecraft.class_437.field_22786 (me.shedaniel.clothconfig2.gui.ClothConfigScreen and net.minecraft.class_437 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @130e116b)
> Exit Code: -1

Other mods which support Mod Menu worked fine (i.e. no crash).

The only mods I use:

```
fabric-api-0.34.10+1.17.jar
modmenu-2.0.0-beta.7.jar
optifabric-1.11.1.jar
preview_OptiFine_1.17_HD_U_G9_pre18.jar
simple-hud-utilities-2.1.3.jar
```

**Comment by koitsu** [comment]
Full stack trace ("Minecraft crash report") attached: [crashreport.txt](https://github.com/johnvictorfs/simple-utilities-mod/files/6635424/crashreport.txt)

**Comment by johnvictorfs** [comment]
Minecraft 1.17 is not supported yet, it will be eventually

**Comment by koitsu** [comment]
Thank you! I wasn't sure if this was related to 1.17 or not. No need to rush a fix on it, just wanted to make sure you were aware!

**Comment by johnvictorfs** [comment]
Added 1.17 support in the newest release: https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/2.2.0
