### ISSUE TITLE
I cant find the mod @ modrinth 

### ISSUE THREAD

**Issue by senare** [johnvictorfs/simple-utilities-mod#45]
I belvie it is only published at CurseForge which is fine but I dont find it at first since I belive it's not published at Modrinth ?

REF => https://modrinth.com/

Canb I help ? Would It be ok If i publish it ?

**Comment by johnvictorfs** [comment]
Hello! I am not quite familiar with modrinth, but do feel free to publish the mod there, just link back to this repository :)

**Comment by johnvictorfs** [comment]
Published the Mod to Modrinth here: https://modrinth.com/mod/simple-hud-utilities

(Not approved as of when I'm commenting this so it may take a while for the url to actually work)

Thanks for the suggestion!
