### ISSUE TITLE
FPS amount is wrong

### ISSUE THREAD

**Issue by DAmNRelentless** [johnvictorfs/simple-utilities-mod#5]
Hey there, I am currently using your mod on Minecraft 1.15.2 with Fabric.
Mod-Version: 1.0.2

It seems like the FPS counter is wrong. It is only half of my FPS to be exact. Not a serious problem but I think you should know.
I also enabled the Optifine FPS counter and I always get my 144 FPS I locked Minecraft to. Your counter shows 72 FPS only so it seems to be half the amount.

I am only using Optifine and your mod.

**Comment by johnvictorfs** [comment]
Hm, that's a weird one, can't replicate it, showing right FPS here, but in my computer my FPS can't really go too much above 100-120, so that may be why, will look into

**Comment by DAmNRelentless** [comment]
I tested it without optifine and it's still the same.
I have a 32:9 display. Maybe that's causing an issue. I don't know.

**Comment by johnvictorfs** [comment]
I published a new release that may or may not fix this issue, I still couldn't reproduce it or notice any changes, but I changed the way I am grabbing the FPS from the Client, so it may have changed this https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/1.0.3

**Comment by DAmNRelentless** [comment]
Seems to be working. Thanks a lot!

**Comment by johnvictorfs** [comment]
Great :)
