### ISSUE TITLE
Coordinates should be floored

### ISSUE THREAD

**Issue by Fixer90JU** [johnvictorfs/simple-utilities-mod#50]
The coordinates should be floored instead of rounded, that way they match how the actual debug screen would show them, as well as have it to where the coordinates change as you change which block you're standing on, instead of halfway across a block.

**Comment by danielospina-b** [comment]
Should actually round down the number (towards 0), because flooring in negative coordinates would show a number below the expected value. (e.g if F3 shows -3.33333 the mod HUD would show -4)

**Comment by Fixer90JU** [comment]
> Should actually round down the number (towards 0), because flooring in negative coordinates would show a number below the expected value. (e.g if F3 shows -3.33333 the mod HUD would show -4)

For sure — thanks for the correction.

**Comment by johnvictorfs** [comment]
Fixed in the latest release https://github.com/johnvictorfs/simple-utilities-mod/releases/tag/2.5.2
