### ISSUE TITLE
Settings are not visible in the Mode menu

### ISSUE THREAD

**Issue by chamchi4444** [johnvictorfs/simple-utilities-mod#72]
Simple utility mode is applied, but the setting window is not visible in the mode menu, so the function cannot be turned off and turned on and set.

**Comment by chamchi4444** [comment]
![캡처](https://user-images.githubusercontent.com/122509018/211993990-4c26dfb2-9a12-4b2d-b827-9e782de04f0d.PNG)
 can't see the upper right setting window as shown in the picture.

**Comment by SoRadGaming** [comment]
What Mod Menu version are you using?

**Comment by chamchi4444** [comment]
I'm using the latest version, 5.0.2.

**Comment by chamchi4444** [comment]
> 어떤 모드 메뉴 버전을 사용하고 있습니까?

I'm using the latest version, 5.0.2.

**Comment by SoRadGaming** [comment]
Maybe try updating the Fabric installer and Fabric API, and redownload ModMenu + this mod. I cannot recreate your issue on my end, it works fine for me; I even tried multiple languages.

**Comment by chamchi4444** [comment]
> Fabric 설치 프로그램 및 Fabric API를 업데이트하고 ModMenu + 이 모드를 다시 다운로드하십시오. 내 쪽에서는 문제를 재현할 수 없습니다. 잘 작동합니다. 나는 심지어 여러 언어를 시도했다.

I deleted Fabric, Mod Menu, and simple hood and downloaded them to the latest version, but the same phenomenon keeps happening...

**Comment by SoRadGaming** [comment]
Try deleting simple_utilities.toml in .minecraft\config

**Comment by chamchi4444** [comment]
> Try deleting simple_utilities.toml in .minecraft\config

I've tried that method as well, but unfortunately, it still hasn't worked out.

**Comment by SoRadGaming** [comment]
I'm all out of ideas; the last thing I can think of is to try the new prerelease version of the mod, https://github.com/SoRadGaming/simple-utilities-mod/releases/tag/2.5.4

**Comment by chamchi4444** [comment]
> I'm all out of ideas; the last thing I can think of is to try the new prerelease version of the mod, https://github.com/SoRadGaming/simple-utilities-mod/releases/tag/2.5.4

Okay, thank you. I'll try again when the new version comes out.

**Comment by PSYQUO** [comment]
Hello, I'd also like to report that the setting buttons is not visible on Mod Menu both on version `2.5.3` and the pre-release version `2.5.4` linked above.

![image](https://user-images.githubusercontent.com/24714104/216769471-9c32b378-ae1a-4ba3-bed7-d4d69dab214d.png)

I've looked at the log and it contains errors pertaining to `simple_utilities`: [latest.log](https://github.com/johnvictorfs/simple-utilities-mod/files/10608748/latest.log)

Some more information that might be useful:
- Minecraft version: `1.19.3`
- Fabric Loader: `0.14.13`
- ModMenu version `5.0.2`

Hope this helps

**Comment by SoRadGaming** [comment]
> Hello, I'd also like to report that the setting buttons is not visible on Mod Menu both on version `2.5.3` and the pre-release version `2.5.4` linked above.
> 
> ![image](https://user-images.githubusercontent.com/24714104/216769471-9c32b378-ae1a-4ba3-bed7-d4d69dab214d.png)
> 
> I've looked at the log and it contains errors pertaining to `simple_utilities`: [latest.log](https://github.com/johnvictorfs/simple-utilities-mod/files/10608748/latest.log)
> 
> Some more information that might be useful:
> 
>     * Minecraft version: `1.19.3`
> 
>     * Fabric Loader: `0.14.13`
> 
>     * ModMenu version `5.0.2`
> 
> 
> Hope this helps

Thanks for the logs and for confirming the issue was not resolved. Do you mind testing this new version? I have updated the internal cloth config fabric API from 7.0.65 to version 9.0.94. https://github.com/SoRadGaming/simple-utilities-mod/releases/tag/2.5.4

**Comment by SoRadGaming** [comment]
I was able to recreate the issue you guys are having; I did not encounter this problem because I had the cloth-config-9.0.94-fabric.jar mod installed separately. My updated 2.5.4 version has fixed this issue by updating the built-in library.

**Comment by PSYQUO** [comment]
Confirming that the new `2.5.4` release fixes the issue. Thanks!

![image](https://user-images.githubusercontent.com/24714104/216827406-8f264da8-f557-4d48-bd38-172fd5e0a46f.png)

**Comment by johnvictorfs** [comment]
Thanks :)
