### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by cootshk** [johnvictorfs/simple-utilities-mod#73]
Update to the latest version of minecraft pls

**Comment by PetyXbron** [comment]
@johnvictorfs what about Minecraft `1.20`? 🙂

**Comment by SoRadGaming** [comment]
I'm getting DM to update my fork on curse forge (I ALREADY HAVE), so ill share the fact I re-wrote the mod from scratch here: https://github.com/SoRadGaming/Simple-HUD-Enhanced
