### ISSUE TITLE
Armor and Sprinting/Movement action HUDs are going over my chat

### ISSUE THREAD

**Issue by RacistTim** [johnvictorfs/simple-utilities-mod#8]
Armor and Sprinting/Movement action HUDs are going over my chat, it would be nice if they could be moved to like the right side or wherever else than just having it in the one current spot.

**Comment by johnvictorfs** [comment]
Yeah, it's pretty annoying, I do have plans to make a setting for that, but I just haven't had the time, it will come eventually
